#!/bin/bash

AMOUNT_CORES=6
MAX_TASKS=${1:-$AMOUNT_CORES}
CORE=0
SECONDS=0

for v in {1..601..50}; do
    for k in {5..20..5}; do
        PID=$!
        taskset -cp $CORE $PID &> /dev/null

        universe=42000
        partitionsize=8400

        echo $PID
        ./knn $universe $partitionsize $v $k &

        CORE=$(( CORE + 1 ))
        if [ $CORE -eq $MAX_TASKS ]; then
                wait
                CORE=0
        fi
    done
done

echo $SECONDS
echo 'Listo'